uname: Unit testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Cunit
      run: sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: make runtest
      run:  make runtest -C 3_Implementation/
